export { router as AuthRouter } from "./auth.js";
export { router as StudentRouter } from "./students.js";
export { router as ProfesoresRouter } from "./profesores.js";
export { router as ProjectsRouter } from "./tesis-project.js";
export { router as CourtRouter } from "./courts.js";
export { router as SearchRouter } from "./search.js";
export { router as EvalRouter } from "./evaluation.js";
export { router as FilesRouter } from "./files.js";
export { router as DefenseRouter } from "./defense.js";
